# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
